name = "NEO"
version = "0.1.0"
defaultTargets = ["SumCheck", "Lookup"]

[[lean_lib]]
name = "SumCheck"

[[lean_lib]]
name = "Lookup"

[[lean_exe]]
name = "neo"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.25.2"
